// GENERATED by scripts/gen-fixtures.mjs — do not edit by hand.
// Source: `guml registry` and `guml highlight`. The compiler owns this vocabulary; a
// second hand-maintained copy is how a highlighter starts lying about the language.

export const TAGS: ReadonlySet<string> = new Set(["alert","avatar","badge","breadcrumb","btn","card","check","col","divider","drawer","empty","faq","footer","form","grid","h","h1","h2","head","hero","img","input","link","list","menu","metric","modal","nav","note","option","p","pagination","progress","row","section","select","sidebar","skeleton","slot","stat","step","stepper","table","tabs","text","tier","toast","toggle","toolbar"]);

/** Tags whose line remainder is prose (`TagKind::Text`). */
export const TEXT_TAGS: ReadonlySet<string> = new Set(["avatar","divider","empty","h","h1","h2","head","img","metric","note","option","p","skeleton","step","text"]);

export const DIRECTIVES: ReadonlySet<string> = new Set(["page","type","data","state","store","on","route","auth","def","js","raw"]);

/** Tags whose children are content lines, not elements (`Registry::children_are_text`). */
export const CONTENT_TAGS: ReadonlySet<string> = new Set(["faq","tier"]);

export const MODIFIERS: ReadonlySet<string> = new Set(["primary","secondary","outline","ghost","quiet","danger","featured","xs","sm","md","lg","xl","center","start","end","between","wrap","tight","loose","full","disabled","loading","readonly","required"]);
