// GENERATED by scripts/gen-fixtures.mjs — do not edit by hand.
// Source: `guml registry` and `guml highlight`. The compiler owns this vocabulary; a
// second hand-maintained copy is how a highlighter starts lying about the language.

export const TAGS: ReadonlySet<string> = new Set(["btn","card","check","col","empty","faq","footer","form","h","h1","h2","head","hero","input","link","list","metric","nav","p","row","section","select","table","tabs","text","tier","toggle"]);

/** Tags whose line remainder is prose (`TagKind::Text`). */
export const TEXT_TAGS: ReadonlySet<string> = new Set(["empty","h","h1","h2","head","metric","p","text"]);

export const DIRECTIVES: ReadonlySet<string> = new Set(["page","type","state","store","data","route","auth","def","js","raw"]);

/** Tags whose children are content lines, not elements (`Registry::children_are_text`). */
export const CONTENT_TAGS: ReadonlySet<string> = new Set(["faq","tier"]);

export const MODIFIERS: ReadonlySet<string> = new Set(["primary","secondary","outline","ghost","quiet","danger","featured","xs","sm","md","lg","xl","center","start","end","between","wrap","tight","loose","full","disabled","loading","readonly","required"]);
