/* GENERATED by scripts/gen-tags.mjs — do not edit.
 *
 * Two lists the external scanner needs, both from the component registry:
 *
 *   GUML_TEXT_TAGS     tags whose line remainder is prose (TagKind::Text)
 *   GUML_CONTENT_TAGS  tags whose indented children are verbatim content lines
 */
#ifndef GUML_TAGS_H
#define GUML_TAGS_H

#define GUML_TEXT_TAGS_COUNT 15

static const char *const GUML_TEXT_TAGS[GUML_TEXT_TAGS_COUNT] = {
    "avatar",
    "divider",
    "empty",
    "h",
    "h1",
    "h2",
    "head",
    "img",
    "metric",
    "note",
    "option",
    "p",
    "skeleton",
    "step",
    "text",
};

#define GUML_CONTENT_TAGS_COUNT 2

static const char *const GUML_CONTENT_TAGS[GUML_CONTENT_TAGS_COUNT] = {
    "faq",
    "tier",
};

#endif
