//! Code generation.
//!
//! The generator is where "convention as compression" is cashed out (report §4.C.4): the
//! model never emits a Tailwind class string, a `useState` setter, an `aria-label`, or a
//! loading state — the compiler owns all of it, which is simultaneously a token saving and a
//! correctness guarantee.
//!
//! **v0.1 scope is deliberately a vertical slice.** The React backend lowers containers, text,
//! and controls end to end (fixture A compiles and runs). Repeaters, forms, resources and
//! optimistic mutations are *reported as unsupported* rather than silently mis-lowered — an
//! honest partial compiler is useful; a quietly wrong one is not.

use guml_ast::{Element, Positional, Program, Value};
use guml_diagnostics::{Diagnostics, Severity, Span};
use std::fmt::Write as _;

pub mod agent;
pub mod expr;
pub mod html;
pub mod json;
pub mod react;
pub mod sourcemap;
pub mod svelte;
pub mod theme;
pub mod wc;

/// Each collection paired with the single boolean field of its row type.
///
/// `.open`/`.done` are the language's way of saying "not in the terminal state" / "in it", and until
/// this existed they lowered to a hardcoded `!it.done`. That is only correct for authors who happen to
/// name the field `done`: a Phase 0 example modelling invoices as `{id, client, amount:number,
/// paid:bool, due:date}` compiled to `invoices.filter((it) => !it.done).length`, which is always zero,
/// with no diagnostic. The analyser now rejects the ambiguous and missing cases (`GUML0065`), so a
/// collection reaching here has exactly one candidate.
///
/// Shared by all three backends deliberately. Three copies of this loop is three chances for React and
/// Svelte to filter on different fields for the same document.
/// Retry with exponential backoff, emitted once per file when the document fetches anything.
///
/// Convention-as-compression at its least glamorous and most useful: every real application needs
/// this, nobody writes it on the first pass, and the hand-written version is usually wrong in one of
/// three ways this one is not.
///
/// * **Only idempotent requests are retried.** A repeated `POST` with no idempotency key creates two
///   rows, so the decision belongs to the *method* and is made here rather than left to a caller who
///   can set the flag on the wrong request.
/// * **Only 5xx and transport failures are retried.** A 404 or a 422 will answer the same way however
///   many times it is asked; retrying it only delays the error the author needs to see.
/// * **An abort is not a failure.** Retrying after the component unmounted is the leak the
///   `AbortController` existed to prevent.
///
/// Emitted rather than imported because a compiled page has no GUML runtime dependency — that is what
/// compiling means here. It costs ~90 tokens of *output* once per file and zero tokens of input.
///
/// Two spellings because the React backend emits TypeScript and the Svelte one emits plain JavaScript.
/// They are held together by a test on the policy rather than on the text, since the type annotations
/// are the only thing that may legitimately differ.
pub const RETRY_TS: &str = r#"/**
 * `fetch` with exponential backoff. Generated by the GUML compiler.
 *
 * Retries only what is safe to repeat — idempotent methods, and only on a transport failure or a 5xx.
 * A 4xx will answer the same way next time, and an abort means the caller no longer wants the answer.
 */
async function retrying(url: string, init: RequestInit = {}, tries = 3): Promise<Response> {
  const idempotent = !init.method || ["GET", "HEAD", "PUT", "DELETE"].includes(init.method);
  let wait = 300;
  for (let attempt = 1; ; attempt++) {
    const last = attempt >= tries || !idempotent;
    try {
      const res = await fetch(url, init);
      if (res.ok || res.status < 500 || last) return res;
    } catch (err) {
      if (last || (err instanceof Error && err.name === "AbortError")) throw err;
    }
    await new Promise((resolve) => setTimeout(resolve, wait));
    wait *= 2;
  }
}

"#;

/// The same policy, untyped, for the Svelte backend's plain-JavaScript `<script>`.
pub const RETRY_JS: &str = r#"  /**
   * `fetch` with exponential backoff. Generated by the GUML compiler.
   *
   * Retries only what is safe to repeat — idempotent methods, and only on a transport failure or a
   * 5xx. A 4xx answers the same way next time, and an abort means the caller stopped caring.
   */
  async function retrying(url, init = {}, tries = 3) {
    const idempotent = !init.method || ["GET", "HEAD", "PUT", "DELETE"].includes(init.method);
    let wait = 300;
    for (let attempt = 1; ; attempt++) {
      const last = attempt >= tries || !idempotent;
      try {
        const res = await fetch(url, init);
        if (res.ok || res.status < 500 || last) return res;
      } catch (err) {
        if (last || err.name === "AbortError") throw err;
      }
      await new Promise((resolve) => setTimeout(resolve, wait));
      wait *= 2;
    }
  }
"#;

/// Response cache with in-flight deduplication and stale-while-revalidate.
///
/// # Why the compiler owns this
///
/// Convention-as-compression again, and this is the clearest case yet: every real application needs all
/// four of these behaviours, none of them is written on the first pass, and each is wrong in a specific
/// way when hand-written.
///
/// * **Deduplication.** Two components reading the same resource in one paint issue two identical
///   requests. Keyed on method and URL, the second awaits the first's promise.
/// * **Stale-while-revalidate.** A remount with a warm cache shows data immediately and refreshes behind
///   it, instead of a skeleton for content the user already saw.
/// * **Invalidation on mutation.** The subtle one. Without it, an optimistic update is followed by a
///   refetch that *serves the cached pre-mutation list* — so the row the user just added visibly
///   disappears, and the bug looks like a broken optimistic update rather than a stale cache.
/// * **Serving stale on failure.** A network error with a warm cache shows the last known data and says
///   it is stale, rather than replacing a working screen with an error. This is the offline story, and it
///   is one branch.
///
/// Only `GET` is cached: caching a `POST` response would return one user's creation to another's request.
/// The window is deliberately short and a module-level constant rather than a knob — a compiler emitting
/// a configurable cache is emitting a configuration surface nobody asked for, and a host that needs a
/// real cache policy has one already.
pub const CACHE_TS: &str = r#"/**
 * Response cache. Generated by the GUML compiler.
 *
 * In-flight deduplication, stale-while-revalidate, invalidation on mutation, and stale-on-failure —
 * the four things every application needs from a fetch layer and nobody writes on the first pass.
 * Only GET is cached; a cached POST would hand one caller another's response.
 */
const GUML_CACHE = new Map<string, { at: number; data: unknown }>();
const GUML_INFLIGHT = new Map<string, Promise<unknown>>();
/** How long a cached response is served without revalidating behind it. */
const GUML_STALE_MS = 30_000;

/** Drop every cached entry whose URL starts with `prefix`. Called after a mutation. */
function invalidate(prefix: string): void {
  for (const key of [...GUML_CACHE.keys()]) {
    if (key.slice(key.indexOf(" ") + 1).startsWith(prefix)) GUML_CACHE.delete(key);
  }
}

async function cached<T>(url: string, init: RequestInit = {}): Promise<T> {
  const method = init.method ?? "GET";
  const key = `${method} ${url}`;
  if (method !== "GET") return read<T>(url, init);

  const hit = GUML_CACHE.get(key);
  const fresh = hit && Date.now() - hit.at < GUML_STALE_MS;
  if (hit && !fresh) {
    // Stale: revalidate behind the value we are about to return. Errors are swallowed here on purpose —
    // the caller already has data, and a background refresh failing is not the caller's problem.
    void refresh<T>(key, url, init).catch(() => {});
  }
  if (hit) return hit.data as T;

  const pending = GUML_INFLIGHT.get(key);
  if (pending) return pending as Promise<T>;
  return refresh<T>(key, url, init);
}

function refresh<T>(key: string, url: string, init: RequestInit): Promise<T> {
  const request = read<T>(url, init)
    .then((data) => {
      GUML_CACHE.set(key, { at: Date.now(), data });
      return data;
    })
    .catch((err: unknown) => {
      // Offline, with something to show: the last known data beats replacing a working screen with an
      // error. The caller is told it is stale so it can say so.
      const hit = GUML_CACHE.get(key);
      if (hit) return hit.data as T;
      throw err;
    })
    .finally(() => GUML_INFLIGHT.delete(key));
  GUML_INFLIGHT.set(key, request as Promise<unknown>);
  return request;
}

async function read<T>(url: string, init: RequestInit): Promise<T> {
  const res = await retrying(url, init);
  if (!res.ok) throw new Error(`Request failed: ${res.status}`);
  return (await res.json()) as T;
}

"#;

/// The same policy, untyped, for the backends that emit plain JavaScript.
///
/// Two spellings for the same reason `RETRY_JS` exists, and held together the same way: by a test on the
/// *policy* rather than on the text, since the type annotations are the only thing that may differ.
pub const CACHE_JS: &str = r#"/**
 * Response cache. Generated by the GUML compiler.
 *
 * In-flight deduplication, stale-while-revalidate, invalidation on mutation, and stale-on-failure.
 * Only GET is cached; a cached POST would hand one caller another's response.
 */
const GUML_CACHE = new Map();
const GUML_INFLIGHT = new Map();
const GUML_STALE_MS = 30_000;

function invalidate(prefix) {
  for (const key of [...GUML_CACHE.keys()]) {
    if (key.slice(key.indexOf(" ") + 1).startsWith(prefix)) GUML_CACHE.delete(key);
  }
}

async function cached(url, init = {}) {
  const method = init.method ?? "GET";
  const key = `${method} ${url}`;
  if (method !== "GET") return read(url, init);

  const hit = GUML_CACHE.get(key);
  const fresh = hit && Date.now() - hit.at < GUML_STALE_MS;
  if (hit && !fresh) {
    void refresh(key, url, init).catch(() => {});
  }
  if (hit) return hit.data;

  const pending = GUML_INFLIGHT.get(key);
  if (pending) return pending;
  return refresh(key, url, init);
}

function refresh(key, url, init) {
  const request = read(url, init)
    .then((data) => {
      GUML_CACHE.set(key, { at: Date.now(), data });
      return data;
    })
    .catch((err) => {
      const hit = GUML_CACHE.get(key);
      if (hit) return hit.data;
      throw err;
    })
    .finally(() => GUML_INFLIGHT.delete(key));
  GUML_INFLIGHT.set(key, request);
  return request;
}

async function read(url, init) {
  const res = await retrying(url, init);
  if (!res.ok) throw new Error(`Request failed: ${res.status}`);
  return await res.json();
}

"#;

/// A React error boundary, emitted **only** for a document that uses an escape hatch.
///
/// # Why the rule is that narrow
///
/// The tempting version is "wrap every page, it costs nothing". It costs something — ~25 lines of output
/// on every page — and more importantly it would be *ceremony*: an error boundary catches errors thrown
/// during render, and the render code here is generated by the compiler from a typechecked expression
/// tree. There is no user code in it to throw.
///
/// Except in exactly one place. A `js` block and a `raw react` block are the two constructs where the
/// compiler's guarantees stop by design — the body is emitted verbatim, never lexed, never checked. That
/// code *can* throw during render, and when it does React unmounts the whole tree and the page goes
/// blank. So the boundary exists to contain the code the compiler does not check, and emitting it
/// anywhere else would be padding.
///
/// The fallback deliberately names the escape hatch as the likely cause. A generic "Something went wrong"
/// sends the reader looking through generated code; naming the one construct the compiler did not verify
/// is the difference between a message and a lead.
pub const ERROR_BOUNDARY_TSX: &str = r#"/**
 * Error boundary. Generated by the GUML compiler.
 *
 * Emitted because this document uses a `js` or `raw` escape hatch — the two places where the compiler's
 * guarantees stop and the body is passed through verbatim. Generated render code cannot throw; that code
 * can, and without a boundary one throw blanks the entire page.
 */
class GumlBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  state: { error: Error | null } = { error: null };

  static getDerivedStateFromError(error: Error) {
    return { error };
  }

  render() {
    if (!this.state.error) return this.props.children;
    return (
      <div role="alert" className="rounded-md border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">
        <p className="font-medium">This view could not render.</p>
        <p className="mt-1">
          {this.state.error.message} — the most likely cause is a `js` or `raw` block, which the GUML
          compiler passes through without checking.
        </p>
      </div>
    );
  }
}

"#;

/// Whether a document uses an escape hatch, and therefore warrants an error boundary.
pub fn uses_escape_hatch(els: &[Element]) -> bool {
    els.iter().any(|el| matches!(el.tag.as_str(), "js" | "raw") || uses_escape_hatch(&el.children))
}

/// The path prefix a mutation on this resource should invalidate.
///
/// The resource's own URL up to its first interpolation, so `PATCH /api/tasks/{id}` invalidates
/// `/api/tasks` — the list the row came from. Trimming at the brace is what makes one mutation invalidate
/// the collection rather than only the row's own URL, which nothing was caching.
pub fn invalidation_prefix(url: &str) -> String {
    let base = url.split('{').next().unwrap_or(url);
    base.trim_end_matches('/').to_string()
}

/// A class list with duplicates removed, first occurrence winning.
///
/// Needed because two sources contribute classes to one element: the theme's rule for the tag, and the
/// layout attributes (`cols`, `gap`, `w`) that a backend folds in afterwards. They overlap by
/// construction — `cols=` has to emit `grid gap-6` so that `card cols=3` becomes a grid, and the `grid`
/// *tag*'s own rule says `grid gap-6` too, so `grid cols=3` produced
/// `class="grid gap-6 grid gap-6 md:grid-cols-3"`.
///
/// Harmless to a browser and not harmless to a reader: emitted code is something a person opens, and a
/// duplicated utility reads as a compiler that does not know what it emitted. Order is preserved because
/// utility frameworks resolve conflicts by source order, so reordering could change the rendering.
pub(crate) fn dedupe_classes(classes: &str) -> String {
    let mut seen = std::collections::BTreeSet::new();
    classes.split_whitespace().filter(|c| seen.insert(*c)).collect::<Vec<_>>().join(" ")
}

/// The HTML element a GUML tag lowers to. `None` means no backend lowers it yet.
///
/// # Why this is shared
///
/// It was two tables. `react.rs` mapped `nav` to `<nav>`, `hero` to `<header>` and `footer` to
/// `<footer>`; `html.rs` had a `_ => "div"` fallback and so emitted a `<div>` for all three. The
/// no-JavaScript output therefore had *no landmarks* — a screen-reader user could not jump to the
/// navigation on a page where the React build let them.
///
/// The two backends already share `classes()`, and a test holds them to producing the same class
/// strings, on the argument that "GUML is an IR" has to be a claim about the language rather than about
/// one emitter. The same argument applies at least as strongly to the *element*, which is what carries
/// the semantics: `every_tag_lowers_to_the_same_element_in_every_backend` now pins it.
///
/// Attributes that depend on the element's own content — a `btn`'s `type`, a `link`'s `href`, an
/// `img`'s `src` — stay with each backend, because they are not a property of the tag.
pub(crate) fn element_for(tag: &str) -> Option<&'static str> {
    Some(match tag {
        "card" | "row" | "col" | "grid" | "skeleton" => "div",
        "section" => "section",
        "nav" => "nav",
        "hero" => "header",
        "footer" => "footer",
        "form" => "form",
        "sidebar" => "aside",
        "h" | "h2" => "h2",
        "h1" => "h1",
        "h3" => "h3",
        // `metric` is a `TagKind::Text` — its line remainder is prose — so it belongs with the other
        // text tags. React emitted a `<div>` for it while this backend emitted a `<p>`; unifying them
        // meant picking one, and a block `div` wrapping a single run of text was the wrong half.
        "p" | "head" | "empty" | "note" | "metric" => "p",
        "text" | "badge" | "avatar" => "span",
        "label" => "label",
        "btn" => "button",
        "link" => "a",
        "check" | "toggle" | "input" => "input",
        "select" => "select",
        "option" => "option",
        "divider" => "hr",
        "img" => "img",
        "progress" => "progress",
        "step" => "li",
        "stepper" => "ol",
        "menu" => "ul",
        "toolbar" | "alert" | "modal" | "drawer" | "toast" => "div",
        "breadcrumb" | "pagination" => "nav",
        "stat" => "dl",
        _ => return None,
    })
}

/// The vocabulary this process compiles against.
///
/// A process-wide value rather than a parameter on `Backend::emit`, for exactly the reason
/// [`theme::active`] gives about the class table: the question "what is this tag" is asked from a dozen
/// places across five backends, several of them deep inside recursive renderers that would each have to
/// grow a `&Registry` argument. A single override point keeps the change here rather than in every
/// emitter.
///
/// Defaults to the builtins, so a caller that never sets one behaves as before. `set` is write-once per
/// process: a compiler run has one vocabulary, and switching mid-run would emit a document against two.
///
/// Before this existed, a backend could only see the *builtin* vocabulary — so a loaded component's
/// `capabilities` were invisible to the `html` backend's runtime check, and its `element` could not be
/// read at all, which is why a registry package validated documents it could not compile.
static ACTIVE_REGISTRY: std::sync::OnceLock<guml_registry::Registry> = std::sync::OnceLock::new();

pub fn registry() -> &'static guml_registry::Registry {
    ACTIVE_REGISTRY.get_or_init(guml_registry::Registry::builtin)
}

/// Install the vocabulary for this process. Returns `Err` with the registry if one is already active.
pub fn set_registry(reg: guml_registry::Registry) -> Result<(), Box<guml_registry::Registry>> {
    ACTIVE_REGISTRY.set(reg).map_err(Box::new)
}

/// What a tag lowers to, when the registry says and the compiler does not already know.
///
/// Returns `(element, import)`. `None` means no loaded entry describes it, and the caller falls back to
/// [`element_for`] and then to reporting the gap.
pub(crate) fn custom_element(tag: &str) -> Option<(&'static str, Option<&'static str>)> {
    let def = registry().get(tag)?;
    let element = def.element.as_deref()?;
    Some((element, def.import.as_deref()))
}

/// Whether a tag cannot work without client-side JavaScript, per its registry entry.
///
/// Read from the registry rather than matched against a list in each backend. Three backends asking
/// "does this need a runtime" is three lists to forget to update; `capabilities.needs_runtime` is the
/// entry's own answer, and a component that declares it gets the right treatment in every backend
/// without any backend naming it.
pub(crate) fn needs_runtime(tag: &str) -> bool {
    registry().get(tag).is_some_and(|c| c.capabilities.needs_runtime)
}

/// The choices a `select` offers, in document order.
///
/// # Why this is shared rather than per-backend
///
/// A `select` emitted **no options at all** until this existed. Every backend produced
/// `<select value={status} onChange={…}>` and nothing inside it — a dropdown with nothing to choose,
/// which is not a partial lowering but a wrong one. It survived because no fixture used `select` with a
/// domain, so neither the snapshots nor `typecheck-emitted` ever saw the empty case.
///
/// Two sources, in order:
///
/// 1. **Authored `option` children.** This is the shape a model reaches for unprompted, because it is
///    the shape HTML has. Accepting it costs nothing and removes an entire class of generation failure.
/// 2. **The bound state's enumerated domain.** `state status=open|closed` already names the choices, and
///    repeating them as children would be the per-line overhead GUML exists to remove.
///
/// The two cannot disagree, because `sema` checks authored options against the domain when there is one
/// and *derives* the domain from them when there is not.
///
/// Deliberately not a desugar pass that rewrites the tree. `guml ast` and the conformance fingerprints
/// are supposed to show what the author wrote; a pass that invented four `option` children would make
/// every `select` case in the suite describe a document nobody wrote.
pub fn select_options(program: &Program, el: &Element) -> Vec<String> {
    let written: Vec<String> = el
        .children
        .iter()
        .filter(|c| c.tag == "option")
        .filter_map(|c| {
            c.content
                .clone()
                .or_else(|| c.label().map(str::to_string))
                .map(|s| s.trim().to_string())
        })
        .filter(|s| !s.is_empty())
        .collect();
    if !written.is_empty() {
        return written;
    }
    el.label()
        .and_then(|name| program.states.iter().find(|s| s.name == name))
        .map(|s| s.domain.clone())
        .unwrap_or_default()
}

pub fn row_bool_fields(program: &guml_ast::Program) -> Vec<(String, String)> {
    let mut out = Vec::new();
    for r in &program.resources {
        let base = r.ty.trim_end_matches("[]");
        let Some(t) = program.types.iter().find(|t| t.name == base) else { continue };
        let mut bools = t.fields.iter().filter(|f| f.ty == "bool");
        if let (Some(f), None) = (bools.next(), bools.next()) {
            out.push((r.name.clone(), f.name.clone()));
        }
    }
    out
}

/// The row fields a free-text `where=` should search, or empty when this is not a free-text filter.
///
/// Both conditions have to hold, and the decision lives here rather than in each backend so React and
/// Svelte cannot disagree about what a document means:
///
/// 1. The bound state has **no domain and holds a string** — `state query=""`. A domain means the filter
///    is enumerated and `where_filter`'s existing cases apply; a number or a boolean is not a query.
/// 2. The row type has at least one **string** field to search. Searching a row of numbers for a
///    substring is not a filter anyone asked for, and returning nothing here means the caller warns
///    instead of emitting a predicate that can never match.
///
/// Declared field types are what decides it, not the field names: `{id, client, amount:number}` searches
/// `id` and `client` and leaves `amount` alone. A field with no declared type is a string, which is the
/// language's default and the reason it is spelled out in `guml_ast::Field`.
pub fn search_fields(program: &Program, resource: &str, filter: &str) -> Vec<String> {
    let Some(state) = program.states.iter().find(|s| s.name == filter) else { return Vec::new() };
    if !state.domain.is_empty() || !matches!(state.init, Value::Str(_)) {
        return Vec::new();
    }
    let Some(r) = program.resources.iter().find(|r| r.name == resource) else { return Vec::new() };
    let base = r.ty.trim_end_matches("[]");
    let Some(t) = program.types.iter().find(|t| t.name == base) else { return Vec::new() };
    t.fields
        .iter()
        .filter(|f| f.ty.is_empty() || f.ty == "string")
        .map(|f| f.name.clone())
        .collect()
}

/// The predicate chain for `where={state}`, or `None` when nothing in the domain can be filtered on.
///
/// `where=` filters a repeater by an enumerated state, so what it filters *by* has to be derived from
/// the domain and the row type together. Three cases, in order:
///
/// 1. **A boolean field.** A single `bool` on the row is a two-state flag, and the domain names its
///    states: `open` is the negation, `done` or the field's own name is the assertion. So
///    `state view=all|open|paid` over `{…, paid:bool}` filters on `paid` — which is the reading a
///    person gives it, and the reading the tabs imply.
/// 2. **A same-name field.** `where={area}` over a row with an `area` field compares them.
/// 3. **Neither**, and the caller warns.
///
/// The first case used to require the field be *named* `done`. That is the third place in this
/// compiler where the same hardcode sat — after the `.open`/`.done` aggregate and the body-less `save`
/// toggle — and here it did not produce a wrong filter but *no* filter: `all|open|paid` fell through
/// to case 3, so the tabs rendered, changed the state, and the table never responded.
///
/// Shared by React and Svelte deliberately. A fourth copy of this reasoning is a fourth chance for two
/// backends to filter the same document differently.
pub fn where_filter(
    source: &str,
    filter: &str,
    domain: &[String],
    fields: &[String],
    text_fields: &[String],
    flag: Option<&str>,
) -> Option<String> {
    // Case 0: a free-text query, from `search_fields` — a domain-less string state, so there is nothing
    // to enumerate and the filter is a substring match over the row's own text.
    //
    // Added because `where=` had refused it, honestly and unhelpfully: `input query` plus
    // `table contacts where={query}` produced two warnings and an unfiltered table, and "a searchable
    // table" is in half of GUML-Bench's categories. The alternative for an author was an escape hatch,
    // and `js` is component-body code — it cannot reach inside the repeater's `map`, so there was no
    // alternative at all.
    if !text_fields.is_empty() {
        let haystack = text_fields.iter().map(|f| format!("it.{f}")).collect::<Vec<_>>().join(", ");
        // An empty query renders everything rather than nothing: `"".includes` is true for every string,
        // which would work by accident here, but only until someone types a space. `trim` first and
        // short-circuit, so a whitespace-only query is also "no filter".
        return Some(format!(
            "{filter}.trim() === \"\"
        ? {source}
        : {source}.filter((it) =>
            [{haystack}].some((v) =>
              String(v).toLowerCase().includes({filter}.trim().toLowerCase()),
            ),
          )"
        ));
    }

    let members: Vec<&String> = domain.iter().filter(|m| *m != "all").collect();
    if members.is_empty() {
        return None;
    }

    // Case 1: every member describes the one boolean field. `flag` comes from the row *type* via
    // `row_bool_fields`, not from guessing at the field-name list — the names alone cannot tell a
    // boolean from a string.
    if let Some(flag) = flag {
        let boolean = |m: &str| match m {
            "open" => Some(format!("{source}.filter((it) => !it.{flag})")),
            _ if m == "done" || m == flag => Some(format!("{source}.filter((it) => it.{flag})")),
            _ => None,
        };
        if members.iter().all(|m| boolean(m).is_some()) {
            return Some(chain(source, filter, &members, |m| boolean(m).unwrap()));
        }
    }

    // Case 2: a row field of the same name holds the member.
    if fields.iter().any(|f| f == filter) {
        return Some(if domain.iter().any(|m| m == "all") {
            format!(
                "{filter} === \"all\" ? {source} : {source}.filter((it) => it.{filter} === {filter})"
            )
        } else {
            format!("{source}.filter((it) => it.{filter} === {filter})")
        });
    }

    None
}

/// A nested ternary, one branch per domain member, falling back to the unfiltered source.
///
/// Indented as the emitted file will read it: this is code a person opens.
fn chain(
    source: &str,
    filter: &str,
    members: &[&String],
    branch: impl Fn(&str) -> String,
) -> String {
    let mut out = String::new();
    for (i, m) in members.iter().enumerate() {
        let pad = "  ".repeat(i);
        let lead = if i == 0 { String::new() } else { format!("\n      {pad}: ") };
        let _ = write!(out, "{lead}{filter} === {m:?}\n      {pad}  ? {}", branch(m));
    }
    let pad = "  ".repeat(members.len().saturating_sub(1));
    let _ = write!(out, "\n      {pad}  : {source}");
    out
}

#[derive(Debug, Clone)]
pub struct OutFile {
    pub path: String,
    pub contents: String,
    /// Line provenance, when the backend recorded it. The driver serialises this to Source Map
    /// v3, because serialising needs the source *text* and only the driver has it.
    ///
    /// Without a map, every stack trace and breakpoint points at generated code the author never
    /// wrote — which the report names as an adoption blocker rather than a nicety (§12.2).
    pub source_map: Option<crate::sourcemap::SourceMap>,
}

#[derive(Debug, Clone, Default)]
pub struct Emitted {
    pub files: Vec<OutFile>,
    pub diagnostics: Diagnostics,
}

pub trait Backend {
    fn name(&self) -> &'static str;
    fn emit(&self, program: &Program) -> Emitted;
}

/// Backends registered in v0.1.
pub fn backend(name: &str) -> Option<Box<dyn Backend>> {
    match name {
        "react" => Some(Box::new(react::ReactBackend)),
        "json" => Some(Box::new(json::JsonBackend)),
        "html" => Some(Box::new(html::HtmlBackend { style: html::Style::Inline })),
        // Same backend, styled by the Tailwind CDN. A separate name rather than a flag, so the
        // preview path is visible in `--help` and never becomes the default by accident.
        "html-cdn" => Some(Box::new(html::HtmlBackend { style: html::Style::Cdn })),
        "svelte" => Some(Box::new(svelte::SvelteBackend)),
        // A custom element, no framework and no build step. The portability target: a compiled document
        // that a browser runs as-is, embeddable where a framework is not on the table.
        "wc" => Some(Box::new(wc::WcBackend)),
        // The agent-UI wire formats. Compile targets and distribution channels, not rivals — see
        // `agent` for why that is the strategically right framing and where the honest caveat is.
        "a2ui" => Some(Box::new(agent::A2uiBackend)),
        "mcp-ui" => Some(Box::new(agent::McpUiBackend)),
        _ => None,
    }
}

pub fn backend_names() -> &'static [&'static str] {
    &["react", "json", "html", "html-cdn", "svelte", "wc", "a2ui", "mcp-ui"]
}

/// HTML elements with no closing tag.
///
/// Keyed on the *element*, not the GUML tag, so it is the same answer for a builtin and for a registry
/// package that declares `"element": "hr"`. Emitting `<hr></hr>` is not parseable markup.
pub(crate) fn is_void_element(element: &str) -> bool {
    matches!(
        element,
        "area"
            | "base"
            | "br"
            | "col"
            | "embed"
            | "hr"
            | "img"
            | "input"
            | "link"
            | "meta"
            | "source"
            | "track"
            | "wbr"
    )
}

// ------------------------------------------------------------------ shared helpers

/// `count` -> `setCount`
pub(crate) fn setter(name: &str) -> String {
    let mut c = name.chars();
    match c.next() {
        Some(f) => format!("set{}{}", f.to_uppercase(), c.as_str()),
        None => "set".to_string(),
    }
}

/// PascalCase component name from a page name.
pub(crate) fn component_name(raw: &str) -> String {
    let mut out = String::new();
    let mut upper = true;
    for ch in raw.chars() {
        if ch.is_alphanumeric() {
            if upper {
                out.extend(ch.to_uppercase());
                upper = false;
            } else {
                out.push(ch);
            }
        } else {
            upper = true;
        }
    }
    if out.is_empty() || out.chars().next().is_some_and(|c| c.is_ascii_digit()) {
        format!("Page{out}")
    } else {
        out
    }
}

/// Invariant 3: a construct a backend cannot lower is *reported*, never silently dropped.
///
/// The backend names itself, because "cannot lower" now means different things in different
/// backends. In React it is a gap to be filled later; in `html` it is permanent and architectural —
/// there is no JavaScript, so there will never be an `onClick`. A message that said "does not yet"
/// about the second case would be telling the reader to wait for something that is not coming.
pub(crate) fn unsupported_in(
    diags: &mut Diagnostics,
    backend: &str,
    span: Span,
    what: impl AsRef<str>,
) {
    let mut d = guml_diagnostics::Diagnostic::warning(
        guml_diagnostics::Code::UnknownTag,
        format!("`{backend}` backend: {}", what.as_ref()),
        span,
    );
    d.severity = Severity::Warning;
    d.help = Some(match backend {
        "html" => "the emitted markup marks the gap with `data-guml-inert`; a construct that needs a runtime cannot work in a no-JavaScript backend".into(),
        _ => "tracked in ROADMAP.md Phase 3; the emitted file marks the gap with a TODO".to_string(),
    });
    diags.push(d);
}

/// The React backend's shorthand, kept so its call sites read unchanged.
pub(crate) fn unsupported(diags: &mut Diagnostics, span: Span, what: impl AsRef<str>) {
    unsupported_in(diags, "react", span, format!("does not yet lower {}", what.as_ref()));
}

pub(crate) fn modifiers_of(el: &Element) -> Vec<&str> {
    el.positionals
        .iter()
        .filter_map(|p| match p {
            Positional::Modifier(m) => Some(m.as_str()),
            _ => None,
        })
        .collect()
}

/// The column headers a repeater declares with `cols=`, or empty.
///
/// # Why `cols` and why a string here
///
/// `cols` is a numeric layout attribute everywhere else — `grid cols=3` sets a column count. On a repeater
/// it lists the headers instead: `table invoices cols="Client, Amount, Due, Paid"`. One attribute name, two
/// types, decided by the tag.
///
/// That asymmetry is deliberate and it is the reason the type checker had to learn per-tag attribute types:
/// a grid's columns are a *count* the compiler generates, and a table's columns are *names* only the author
/// knows. Reusing the name keeps the surface small, and reusing the meaning would have been wrong.
///
/// Comma-separated rather than a repeated attribute, because a duplicate attribute is `GUML0082` and
/// changing that to allow one exception would weaken a rule that catches real mistakes.
///
/// Trailing empties are dropped, so `cols="A, B,"` is two columns — a trailing comma in a hand-written list
/// is a typo, not a request for a blank column.
pub fn column_headers(el: &Element) -> Vec<String> {
    let Some(value) = el.attr("cols") else { return Vec::new() };
    let Some(text) = value.as_text() else { return Vec::new() };
    text.split(',').map(str::trim).filter(|s| !s.is_empty()).map(str::to_string).collect()
}

/// The `<thead>` block for a tabular repeater, or `None` when it declares no `cols=`.
///
/// Shared, and by invariant 8 it has to be: three backends emit a table, and three copies of "a header cell
/// carries `scope=\"col\"`" is three chances for one of them to forget. The only per-backend difference is
/// the attribute name — `className` in JSX, `class` everywhere else — so that is the parameter.
///
/// `scope="col"` is the header/cell association itself. It is exactly the kind of plumbing invariant 4 puts
/// in the compiler rather than in the source: a model asked to remember it will forget, and the failure is
/// invisible until someone uses a screen reader.
pub(crate) fn table_head(el: &Element, pad: &str, attr: &str) -> Option<String> {
    let headers = column_headers(el);
    if headers.is_empty() {
        return None;
    }
    let class = theme::active().classes("th", &[]);
    let class_attr = if class.is_empty() { String::new() } else { format!(" {attr}={class:?}") };
    let mut out = format!("{pad}  <thead>\n{pad}    <tr>\n");
    for h in &headers {
        let _ =
            writeln!(out, "{pad}      <th scope=\"col\"{class_attr}>{}</th>", html_escape_text(h));
    }
    let _ = write!(out, "{pad}    </tr>\n{pad}  </thead>\n");
    Some(out)
}

/// Report what is wrong with a tabular repeater's `cols=`, if anything.
///
/// Two failures, and the second is the nastier one:
///
/// * **No `cols=` at all.** A data table with no header row is an accessibility defect rather than a style
///   choice — a screen reader has nothing to announce a cell against. The compiler cannot invent the names,
///   because only the author knows what the columns mean, so it reports.
/// * **A count that does not match the row template.** Every header would sit one column left of its data.
///   That reads as correct at a glance, which makes it worse than an unlabelled table.
pub(crate) fn check_columns(diags: &mut Diagnostics, backend: &str, el: &Element, cells: usize) {
    let headers = column_headers(el);
    if headers.is_empty() {
        unsupported_in(
            diags,
            backend,
            el.span,
            "a `table` with no `cols=`, so its columns have no headers and a screen reader cannot \
             associate a cell with one — add `cols=\"First, Second\"`",
        );
    } else if headers.len() != cells {
        unsupported_in(
            diags,
            backend,
            el.span,
            format!(
                "`cols=` names {} column(s) but the row template renders {cells}; the headers would not \
                 line up with the data",
                headers.len()
            ),
        );
    }
}

/// Minimal text escaping for a header, which is author-written text in an element body.
fn html_escape_text(s: &str) -> String {
    s.replace('&', "&amp;").replace('<', "&lt;").replace('>', "&gt;")
}

/// Classes from the *layout* attributes — `cols`, `gap`, `w`.
///
/// # Why shared, and the drift that made it necessary
///
/// These are presentation, so they join the class list rather than becoming DOM properties: `cols={3}` on a
/// `<section>` is not valid HTML, which `tsc` caught on the landing fixture. React had that logic and no
/// other backend did, so `grid cols=3` came out as `grid gap-6 md:grid-cols-3` in React and plain
/// `grid gap-6` everywhere else — the same document with three columns in one representation and an
/// unspecified number in the others. Nothing failed, because each backend's snapshot only agreed with
/// itself, and the html output is the one a no-JavaScript build ships.
///
/// A repeater's `cols` is skipped: there it is the header list, not a column count.
pub fn layout_classes(el: &Element) -> Vec<String> {
    let mut out = Vec::new();
    for a in &el.attrs {
        match a.name.as_str() {
            "cols" if !is_tabular(el) && el.tag != "list" => {
                if let Value::Num(n) = &a.value {
                    out.push(format!("grid gap-6 md:grid-cols-{}", *n as i64));
                }
            }
            "gap" => {
                if let Value::Num(n) = &a.value {
                    out.push(format!("gap-{}", *n as i64));
                }
            }
            "w" => {
                if let Some(w) = a.value.as_text() {
                    out.push(format!("max-w-{w}"));
                }
            }
            _ => {}
        }
    }
    out
}

/// A tag's theme classes plus its layout classes, deduplicated — what every backend should put in `class`.
pub fn class_list(el: &Element) -> String {
    let mods: Vec<&str> = el
        .positionals
        .iter()
        .filter_map(|p| match p {
            Positional::Modifier(m) => Some(m.as_str()),
            _ => None,
        })
        .collect();
    let mut all = theme::active().classes(&el.tag, &mods);
    for extra in layout_classes(el) {
        if !all.is_empty() {
            all.push(' ');
        }
        all.push_str(&extra);
    }
    dedupe_classes(&all)
}

/// Whether this repeater should lower to a real `<table>`.
///
/// `table` always does, and `list` never does. The tag is the author's statement of intent, and honouring it
/// is what makes `table` mean anything: it emitted a `<ul>` in every backend until now, so a document that
/// asked for tabular data got a list of rows with no columns, no headers and no header association for a
/// screen reader. `scripts/render-emitted.mjs` has asserted "table without header cells" since it was
/// written and the assertion had never once fired, because no `<table>` was ever emitted to test.
pub fn is_tabular(el: &Element) -> bool {
    el.tag == "table"
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn setter_naming() {
        assert_eq!(setter("count"), "setCount");
        assert_eq!(setter("draft"), "setDraft");
    }

    #[test]
    fn component_naming() {
        assert_eq!(component_name("Counter"), "Counter");
        assert_eq!(component_name("task list"), "TaskList");
        assert_eq!(component_name("landing-page"), "LandingPage");
    }
}
