"""Type stubs for the native extension.

Everything here returns `str` — JSON for structured results. The typed, documented surface is
`guml/__init__.py`, which parses these into dataclasses; see that module's docstring for why the
split falls here.
"""

def version() -> str: ...
def spec() -> str: ...
def backends() -> list[str]: ...
def check(source: str, level: str = "app") -> str: ...
def compile(source: str, backend: str = "react", level: str = "app") -> str: ...
def format(source: str) -> str: ...
def canonical(source: str) -> str: ...
def fix(source: str, max_rounds: int = 3) -> str: ...
def repair(source: str, max_rounds: int = 3) -> str: ...
def capabilities(source: str, backend: str = "html") -> str: ...
def stylesheet() -> str: ...
def registry(tags: list[str] | None = None) -> str: ...
