/**
 * Generates src/tags.h — the two tag lists the external scanner needs.
 *
 * The scanner has to make two decisions a context-free grammar cannot, and both need the component
 * registry:
 *
 *   1. **Is this line's remainder prose?** True for a `TagKind::Text` tag. `p Press the button` is prose;
 *      `btn Decrement ghost` is a label and a modifier.
 *   2. **Are this block's lines verbatim?** True inside a `tier` or `faq`, whose children are content
 *      lines rather than elements. Without this list the scanner offered a verbatim line wherever the
 *      grammar allowed one — and the grammar allows both shapes in a body, so `card A` / `p One` parsed
 *      the child as a content line instead of an element.
 *
 * Both lists are generated for the same reason the TextMate grammar is: a hand-maintained copy is a
 * second vocabulary that can drift from the compiler. This project has been bitten by exactly that twice,
 * both times caught only because somebody thought to compare the two.
 *
 * Run `npm run gen:tags` after changing the registry. `npm run check:tags` fails if it is stale.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..", "..", "..");
const out = join(here, "..", "src", "tags.h");

const registry = execFileSync("cargo", ["run", "-q", "-p", "guml-cli", "--", "registry"], {
  cwd: repoRoot,
  encoding: "utf8",
});

// `guml registry` prints `name  Kind  doc` per component, then named lists.
const textTags = registry
  .split("\n")
  .map((line) => line.trim().split(/\s+/))
  .filter((cols) => cols.length >= 2 && cols[1] === "Text")
  .map((cols) => cols[0])
  .sort();

const namedList = (label) => {
  const line = registry.split("\n").find((l) => l.startsWith(`${label}:`));
  if (!line) return [];
  return line
    .slice(label.length + 1)
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .sort();
};
const contentTags = namedList("content-children");

// Refuse to write a truncated list. A silently empty list is the worst outcome: the scanner would stop
// emitting PROSE entirely and every prose line would parse as a pile of identifiers.
if (textTags.length < 5) {
  console.error(`only ${textTags.length} text tags found — refusing to write a truncated list`);
  process.exit(1);
}
if (contentTags.length < 1) {
  console.error("no content-children tags found — refusing to write a truncated list");
  process.exit(1);
}

const list = (name, tags) =>
  `#define ${name}_COUNT ${tags.length}\n\n` +
  `static const char *const ${name}[${name}_COUNT] = {\n` +
  `${tags.map((t) => `    "${t}",`).join("\n")}\n};\n`;

const body = `/* GENERATED by scripts/gen-tags.mjs — do not edit.
 *
 * Two lists the external scanner needs, both from the component registry:
 *
 *   GUML_TEXT_TAGS     tags whose line remainder is prose (TagKind::Text)
 *   GUML_CONTENT_TAGS  tags whose indented children are verbatim content lines
 */
#ifndef GUML_TAGS_H
#define GUML_TAGS_H

${list("GUML_TEXT_TAGS", textTags)}
${list("GUML_CONTENT_TAGS", contentTags)}
#endif
`;

const previous = (() => {
  try {
    return readFileSync(out, "utf8");
  } catch {
    return "";
  }
})();

if (process.argv.includes("--check")) {
  if (previous !== body) {
    console.error("src/tags.h is stale — the registry changed. Run: npm run gen:tags");
    process.exit(1);
  }
  console.log(
    `tag lists are current (${textTags.length} text, ${contentTags.length} content-children)`,
  );
} else {
  writeFileSync(out, body, "utf8");
  console.log(
    `wrote ${textTags.length} text tags and ${contentTags.length} content-children tags to src/tags.h`,
  );
}
